In [2]:
import pandas as pd

# Читаем файл melb_data.csv
melb_data = pd.read_csv('data/melb_data.csv', sep=',')

Фильтрация в DataFrame — это получение новой таблицы путем вырезания строк, не удовлетворяющих поставленному условию.

Классический способ фильтрации в DataFrame — фильтрация с помощью масок.

Маской называется Series, которая состоит из булевых значений, при этом значения True соответствуют тем индексам, для которых заданное условие выполняется, в противном случае ставится значение False (например, цена больше 2 млн).

In [3]:
mask = melb_data['Price'] > 2000000
display(mask)

0        False
1        False
2        False
3        False
4        False
         ...
13575    False
13576    False
13577    False
13578     True
13579    False
Name: Price, Length: 13580, dtype: bool

Для фильтрации нужно просто подставить переменную mask в индексацию DataFrame. Маска показывает, какие строки нужно оставлять в результирующем наборе, а какие — убирать.

In [4]:
# Выводим первые 5 строк отфильтрованной таблицы
display(melb_data[mask].head())

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
80,80,Albert Park,112 Beaconsfield Pde,3,h,2850000.0,PI,Buxton,4/03/2017,3.3,...,0.0,211.0,198.0,1890.0,Port Phillip,-37.8481,144.9499,Southern Metropolitan,3280.0,"-37.8481, 144.9499"
85,85,Albert Park,104 Richardson St,4,h,2300000.0,S,Marshall,7/05/2016,3.3,...,1.0,153.0,180.0,1880.0,Port Phillip,-37.8447,144.9523,Southern Metropolitan,3280.0,"-37.8447, 144.9523"
88,88,Albert Park,29 Faussett St,2,h,2120000.0,S,Greg,10/09/2016,3.3,...,1.0,199.0,107.0,1900.0,Port Phillip,-37.8422,144.9554,Southern Metropolitan,3280.0,"-37.8422, 144.9554"
92,92,Albert Park,2 Dundas Pl,3,h,2615000.0,S,Cayzer,10/12/2016,3.3,...,1.0,177.0,181.0,1880.0,Port Phillip,-37.8415,144.9585,Southern Metropolitan,3280.0,"-37.8415, 144.9585"
93,93,Albert Park,23 Finlay St,5,h,2100000.0,S,Greg,10/12/2016,3.3,...,1.0,237.0,126.0,1970.0,Port Phillip,-37.8436,144.9557,Southern Metropolitan,3280.0,"-37.8436, 144.9557"

В результате выполнения фильтрации возвращается новый DataFrame, полученный из исходного, при этом исходная таблица melb_data остается без изменений.

Также вовсе не обязательно заносить маску в отдельную переменную — можно сразу вставить условие в операцию индексации DataFrame.

In [8]:
# Сразу вставляем условие в операцию индексации
display(melb_data[melb_data['Price'] > 2000000])

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
80,80,Albert Park,112 Beaconsfield Pde,3,h,2850000.0,PI,Buxton,4/03/2017,3.3,...,0.0,211.0,198.0,1890.0,Port Phillip,-37.84810,144.94990,Southern Metropolitan,3280.0,"-37.8481, 144.9499"
85,85,Albert Park,104 Richardson St,4,h,2300000.0,S,Marshall,7/05/2016,3.3,...,1.0,153.0,180.0,1880.0,Port Phillip,-37.84470,144.95230,Southern Metropolitan,3280.0,"-37.8447, 144.9523"
88,88,Albert Park,29 Faussett St,2,h,2120000.0,S,Greg,10/09/2016,3.3,...,1.0,199.0,107.0,1900.0,Port Phillip,-37.84220,144.95540,Southern Metropolitan,3280.0,"-37.8422, 144.9554"
92,92,Albert Park,2 Dundas Pl,3,h,2615000.0,S,Cayzer,10/12/2016,3.3,...,1.0,177.0,181.0,1880.0,Port Phillip,-37.84150,144.95850,Southern Metropolitan,3280.0,"-37.8415, 144.9585"
93,93,Albert Park,23 Finlay St,5,h,2100000.0,S,Greg,10/12/2016,3.3,...,1.0,237.0,126.0,1970.0,Port Phillip,-37.84360,144.95570,Southern Metropolitan,3280.0,"-37.8436, 144.9557"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13521,13521,Port Melbourne,44 Garton St,4,t,2455000.0,SP,Marshall,26/08/2017,3.5,...,2.0,123.0,0.0,2010.0,NaN,-37.83349,144.94840,Southern Metropolitan,8648.0,"-37.83349, 144.9484"
13523,13523,Prahran,69 Greville St,4,h,2668000.0,S,Biggin,26/08/2017,4.6,...,2.0,383.0,126.0,1970.0,NaN,-37.84879,144.98882,Southern Metropolitan,7717.0,"-37.84879, 144.98882"
13553,13553,Surrey Hills,20 Albert Cr,4,h,2720000.0,S,Kay,26/08/2017,10.2,...,2.0,1005.0,126.0,1920.0,NaN,-37.82421,145.10352,Southern Metropolitan,5457.0,"-37.82421, 145.10352"
13555,13555,Surrey Hills,3 Oak St,4,h,3100000.0,VB,Marshall,26/08/2017,10.2,...,3.0,832.0,126.0,1970.0,NaN,-37.83564,145.10919,Southern Metropolitan,5457.0,"-37.83564, 145.10919"
13578,13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0,"-37.85908, 144.89299"

In [9]:
# Найдем количество зданий с тремя комнатами. Для этого отфильтруем таблицу по условию:
# обратимся к результирующей таблице по столбцу Rooms и найдем число строк в ней с помощью атрибута shape
display(melb_data[melb_data['Rooms']==3].shape[0])

5881

Условия можно комбинировать через операторы & (логическое И) и | (логическое ИЛИ). Условия при этом заключаются в скобки.

In [12]:
# Находим число трехкомнатных домов с ценой менее 300 тысяч
display(melb_data[(melb_data['Rooms'] == 3) & (melb_data['Price'] < 300000)].shape[0])

3

In [13]:
# Теперь найдем количество домов с ценой менее 300 тысяч, у которых либо число комнат равно 3, либо
# площадь более 100 квадратных метров
display(melb_data[(melb_data['Price'] < 300000) & ((melb_data['Rooms'] == 3)|(melb_data['BuildingArea'] > 100))].shape[0])

68

Использование обычных операторов AND и OR будет неверным и приведет к ошибке, так как они выполняют логические операции между двумя булевыми числами. В нашем случае слева и справа от оператора стоят маски (объекты Series), для которых логическую операцию надо совершить поэлементарно, а операторы AND и OR для такого не предназначены.

Фильтрацию часто сочетают со статистическими методами.

In [3]:
# Найдем максимальное количество комнат в таунхаусах
melb_data[melb_data['Type'] == 't']['Rooms'].max()

5

In [4]:
# Найдем медианную площадь здания у объектов, чья цена выше средней
mean_price = melb_data['Price'].mean()
display(melb_data[melb_data['Price'] > mean_price]['BuildingArea'].median())

126.0

Фильтрация также находит применение в очистке данных.

Под очисткой данных понимается удаление из данных аномальных значений (выбросов), пропусков и данных, которые не несут информацию.

Причин появления таких дефектов в данных множество: неправильная передача по сети, неверная выгрузка из базы, человеческий фактор и т.д.
Проблема аномальных значений состоит в том, что если мы обучаем модель на данных, содержащих выбросы, то мы имеем шансы получить менее верный прогноз.

In [6]:
# У скольких объектов недвижимости отсутствуют ванные комнаты
display(melb_data[melb_data['Bathroom'] == 0].shape[0])

34

In [8]:
# Сколько в таблице объектов недвижимости, которые были проданы риэлторской компанией Nelson
# и стоимость которых составила больше 3 миллионов
display(melb_data[(melb_data['SellerG'] == 'Nelson') & (melb_data['Price'] > 3000000)].shape[0])

5

In [10]:
# Минимальная стоимость участка без здания (площадь здания равна 0) в таблице melb_data
display(melb_data[melb_data['BuildingArea'] == 0]['Price'].min())

412500.0

In [21]:
# Какова средняя цена объектов недвижимости с ценой менее одного миллиона,
# в которых либо количество комнат больше пяти, либо здание моложе 2015 года?
mean_price = (
    melb_data[
        (melb_data['Price'] < 1_000_000) &
        ((melb_data['Rooms'] > 5) | (melb_data['YearBuilt'] > 2015))
    ]['Price']
    .mean()
)

round(mean_price)

769239

In [22]:
# В каком районе Мельбурна чаще всего продаются виллы и коттеджи (тип здания — h)
# с ценой меньше 3 миллионов
display(melb_data[
    (melb_data['Type'] == 'h') &
    (melb_data['Price'] < 3_000_000)
    ]['Regionname'].mode())

0    Northern Metropolitan
Name: Regionname, dtype: object