In [1]:
import pandas as pd
# Читаем файл melb_data.csv
melb_data = pd.read_csv('data/melb_data.csv', sep=',')

In [2]:
melb_df = melb_data.copy()
melb_df.head()

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,202.0,126.0,1970.0,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0,"-37.7996, 144.9984"
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0,"-37.8079, 144.9934"
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0,"-37.8093, 144.9944"
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1.0,94.0,126.0,1970.0,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0,"-37.7969, 144.9969"
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0,"-37.8072, 144.9941"

Формат DATETIME

Многие выгрузки из систем и баз данных имеют свой служебный формат:

- 2018-11-09 15:45:21;
- 11/09/2018 3:45:20 PM;
- 2018-11-09T15:45:21.2984

Для всех этих случаев необходимо задавать формат распознавания дат и уметь сравнивать их между собой. Для этого был создан единый способ обозначения даты и времени.

Таким форматом в Pandas является формат datetime, который записывается как YYYY-MM-DD HH: MM: SS, то есть составляющие времени указываются в порядке: год, месяц, день, час, минута, секунда.

В наших данных дата записана в виде DD/MM/YYYY

In [3]:
display(melb_df['Date'])

0         3/12/2016
1         4/02/2016
2         4/03/2017
3         4/03/2017
4         4/06/2016
            ...
13575    26/08/2017
13576    26/08/2017
13577    26/08/2017
13578    26/08/2017
13579    26/08/2017
Name: Date, Length: 13580, dtype: object

Для преобразования столбцов с датами, записанными в распространенных форматах, в формат datetime можно воспользоваться функцией pandas.to_datetime(). В нашем случае в функции нужно указать параметр dayfirst=True, который будет обозначать, что в первоначальном признаке первым идет день. Преобразуем столбец Date в формат datetime, передав в него функцию

In [4]:
melb_df['Date'] = pd.to_datetime(melb_df['Date'], dayfirst=True)
display(melb_df['Date'])

0       2016-12-03
1       2016-02-04
2       2017-03-04
3       2017-03-04
4       2016-06-04
           ...
13575   2017-08-26
13576   2017-08-26
13577   2017-08-26
13578   2017-08-26
13579   2017-08-26
Name: Date, Length: 13580, dtype: datetime64[ns]

В результате мы переопределяем признак Date в формат datetime. При этом так как в изначальном варианте время не было указано, то и после преобразования оно опускается.

Стоит обратить внимание, что изменился тип данных столбца Date, теперь его тип — datetime64.

Тип данных datetime позволяет с помощью специального аксессора dt выделять составляющие времени из каждого элемента столбца, такие как:

- date — дата;

- year, month, day — год, месяц, день;

- time — время;

- hour, minute, second — час, минута, секунда;

- dayofweek — номер дня недели, от 0 до 6, где 0 — понедельник, а 6 — воскресенье;

- day_name — название дня недели;

- dayofyear — порядковый день года;

- quarter — квартал (интервал в 3 месяца).

Аксессор — это атрибут столбца, хранящий переменные, которые были строковым представлением времени, а затем были изменены в помощью pd.to_datetime().

К аксессору нельзя обратиться, если столбец не приведен к типу datetime.

Обратившись по атрибуту dt.year в столбце Date, можно достать год продажи и понять, за какой интервал времени (в годах) представлены наши данные, а также на какой год приходится наибольшее число продаж.

In [5]:
years_sold = melb_df['Date'].dt.year
print(years_sold)
print('Min year sold:', years_sold.min())
print('Max year sold:', years_sold.max())
print('Mode year sold:', years_sold.mode()[0])

0        2016
1        2016
2        2017
3        2017
4        2016
         ...
13575    2017
13576    2017
13577    2017
13578    2017
13579    2017
Name: Date, Length: 13580, dtype: int32
Min year sold: 2016
Max year sold: 2017
Mode year sold: 2017

В результате обращения к атрибуту datetime melb_df['Date'].dt.year мы получаем объект Series, в котором в качестве значений выступают годы продажи объектов недвижимости. Мы можем занести результат в переменную years_sold и далее работать с ней как с обычным столбцом серии — вычислять минимум, максимум и модальное значение (моду).

Из результатов видно, что данные представлены за интервал с 2016 по 2017 год, и наибольшее число объектов было продано в 2017 году.

Так как модальных значений в столбце может быть несколько, метод mode() возвращает объект Series, даже если мода в данных только одна. Чтобы сохранить стилистику вывода информации о годе продажи и выводить только число, а не Series, мы обращаемся к результату работы метода mode() по индексу 0.

Теперь вычислим, на какие месяцы приходится пик продаж объектов недвижимости. Для этого выделим атрибут dt.month и на этот раз занесем результат в столбец MonthSale, а затем найдем относительную частоту продаж для каждого месяца от общего числа продаж — для этого используем value_counts() с параматером normalize (вывод в долях).

In [6]:
melb_df['MonthSale'] = melb_df['Date'].dt.month
melb_df['MonthSale'].value_counts(normalize=True)

MonthSale
5     0.149411
7     0.145950
9     0.135862
6     0.134757
8     0.114138
11    0.082032
4     0.069882
3     0.049926
12    0.044698
10    0.040574
2     0.032622
1     0.000147
Name: proportion, dtype: float64

Из результатов становится ясно, что наибольшее количество продаж недвижимости приходится на май, июль и сентябрь (5, 7, 9 месяцы). Месяцами застоя являются октябрь, февраль и январь (10, 2, 1).

Работа с интервалами

Часто бывает ситуация, что необходимо вычислять интервалы между двумя временными промежутками. Например, можно вычислить, сколько дней прошло с 1 января 2016 года до момента продажи объекта. Для этого можно просто найти разницу между датами продаж и заявленной датой, представленной в формате datetime

In [7]:
delta_days = melb_df['Date'] - pd.to_datetime('2016-01-01')
display(delta_days)

0       337 days
1        34 days
2       428 days
3       428 days
4       155 days
          ...
13575   603 days
13576   603 days
13577   603 days
13578   603 days
13579   603 days
Name: Date, Length: 13580, dtype: timedelta64[ns]

В результате получаем серию, элементами которой является количество дней, которое прошло с 1 января 2016 года. Данные такого формата относятся к типу timedelta.

Чтобы превратить количество дней из формата интервала в формат целого числа дней, можно воспользоваться аксессором dt для формата timedelta и извлечь из него атрибут days:

In [8]:
display(delta_days.dt.days)

0        337
1         34
2        428
3        428
4        155
        ...
13575    603
13576    603
13577    603
13578    603
13579    603
Name: Date, Length: 13580, dtype: int64

Создадим признак возраста объекта недвижимости в годах на момент продажи. Для этого выделим из столбца с датой продажи год и вычтем из него год постройки здания. Результат оформим в виде столбца AgeBuilding

In [10]:
melb_df['AgeBuilding'] = melb_df['Date'].dt.year - melb_df['YearBuilt']
display(melb_df['AgeBuilding'].astype('int16'))

0         46
1        116
2        117
3         47
4          2
        ...
13575     36
13576     22
13577     20
13578     97
13579     97
Name: AgeBuilding, Length: 13580, dtype: int16

Столбец AgeBuilding дублирует информацию из столбца YearBuilt. Поэтому есть смысл оставить возраст здания, так как он более наглядный, а год постройки удалить из таблицы.

In [11]:
melb_df = melb_df.drop('YearBuilt', axis=1)

Создайте в таблице melb_df признак WeekdaySale (день недели). Найдите, сколько объектов недвижимости было продано в выходные (суббота и воскресенье), результат занесите в переменную weekend_count

In [24]:
melb_df['WeekdaySale'] = melb_df['Date'].dt.dayofweek
weekend_count = melb_df[(melb_df['WeekdaySale'] == 5) | (melb_df['WeekdaySale'] == 6)].shape[0]
display(weekend_count)

12822

In [2]:
import pandas as pd

ufo_data = pd.read_csv('https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv')
ufo_df = ufo_data.copy()

In [3]:
display(ufo_df['Time'])

0          6/1/1930 22:00
1         6/30/1930 20:00
2         2/15/1931 14:00
3          6/1/1931 13:00
4         4/18/1933 19:00
               ...
18236    12/31/2000 23:00
18237    12/31/2000 23:00
18238    12/31/2000 23:45
18239    12/31/2000 23:45
18240    12/31/2000 23:59
Name: Time, Length: 18241, dtype: object

In [4]:
ufo_df['Time'] = pd.to_datetime(ufo_df['Time'], dayfirst=False)
display(ufo_df['Time'])

0       1930-06-01 22:00:00
1       1930-06-30 20:00:00
2       1931-02-15 14:00:00
3       1931-06-01 13:00:00
4       1933-04-18 19:00:00
                ...
18236   2000-12-31 23:00:00
18237   2000-12-31 23:00:00
18238   2000-12-31 23:45:00
18239   2000-12-31 23:45:00
18240   2000-12-31 23:59:00
Name: Time, Length: 18241, dtype: datetime64[ns]

In [5]:
years_seen = ufo_df['Time'].dt.year
print(years_seen.mode()[0])

1999

In [10]:
ufo_df['Date'] = ufo_df['Time'].dt.date
nevada_dates = ufo_df[ufo_df['State'] == 'NV']
display(nevada_dates)
print(round(nevada_dates['Date'].diff().dt.days.mean()))

,City,Colors Reported,Shape Reported,State,Time,Date
76,Las Vegas,NaN,DISK,NV,1947-07-15 10:00:00,1947-07-15
172,Nellis AFB,NaN,DISK,NV,1952-02-17 18:00:00,1952-02-17
565,Fallon,NaN,OVAL,NV,1959-09-15 00:00:00,1959-09-15
566,Goldfield,NaN,LIGHT,NV,1959-09-15 01:00:00,1959-09-15
613,NaN,NaN,DISK,NV,1960-07-01 12:00:00,1960-07-01
...,...,...,...,...,...,...
17447,Laughlin,NaN,FORMATION,NV,2000-09-16 22:00:00,2000-09-16
17567,Las Vegas,NaN,SPHERE,NV,2000-09-30 22:25:00,2000-09-30
17617,Las Vegas,RED YELLOW,OTHER,NV,2000-10-06 20:25:00,2000-10-06
17890,Reno,NaN,TRIANGLE,NV,2000-11-07 02:15:00,2000-11-07
18104,Las Vegas,NaN,TRIANGLE,NV,2000-12-10 17:30:00,2000-12-10

69